- hosts: repo.luxor.cloud
  vars_files: vars/vault.yaml
  pre_tasks:
  - name: update apt
    apt:
      update_cache: true
  - name: install rsync # Need to install rsync because nexus role needs it
    apt:
      name: rsync
  roles:
  - role: geerlingguy.java
    java_packages:
    - openjdk-8-jdk
  - role: ansible-thoteam.nexus3-oss
