nginx_cleanup_config: true
nginx_http_template_enable: true
nginx_http_template:
  nexus:
    template_file: http/default.conf.j2
    conf_file_name: repo.luxor.cloud.conf
    conf_file_location: /etc/nginx/conf.d/
    servers:
      nexus:
        listen:
          listen_localhost:
            port: 443
            ssl: true
        server_name: repo.luxor.cloud
        ssl:
          cert: /etc/ssl/certs/cloudflare_origin.crt
          key: /etc/ssl/private/cloudflare_origin.key
        reverse_proxy:
          locations:
            nexus:
              location: /
              proxy_pass: "http://{{ hostvars['repo.luxor.cloud'].private_ipv4_address }}:8081"
              proxy_set_header:
                header_host:
                  name: Host
                  value: $host
