nginx_cleanup_config: true
nginx_http_template_enable: true
nginx_http_template:
  nexus:
    template_file: http/default.conf.j2
    conf_file_name: repo.luxor.cloud.conf
    conf_file_location: /etc/nginx/conf.d/
    servers: 
      nexus:
        listen:
          listen_localhost:
            port: 80
            ssl: false
        server_name: repo.luxor.cloud
        reverse_proxy:
          locations:
            nexus_site:
              location: /
              proxy_pass: http://159.69.20.113:8081
              proxy_set_header:
                header_host:
                  name: Host
                  value: $host
        
                 
