---
- name: Install python3-pip
  apt:
    name: python3-pip

- name: Install pip deps
  pip:
    name: 
      - passlib
      - bcrypt

- name: Copy service file
  template:
    src: docker-registry.service.j2
    dest: /etc/systemd/system/docker-registry.service

- name: Ensure docker-registry is stopped
  systemd:
    enabled: no
    state: stopped
    daemon_reload: yes
    name: docker-registry.service

- name: "Remove {{ registry_htpasswd_path }}"
  file:
    path: "{{ registry_htpasswd_path }}"
    state: absent

- name: "Generate {{ registry_htpasswd_path }}"
  htpasswd:
    path: "{{ registry_htpasswd_path }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    create: yes
    crypt_scheme: bcrypt
  loop: "{{ registry_htpasswd_users }}"

- name: Copy TLS certificate
  copy: content="{{ registry_tls_cert }}" dest={{ registry_tls_cert_path }}
  when: registry_tls_cert is defined

- name: Copy TLS key
  copy: content="{{ registry_tls_key }}" dest={{ registry_tls_key_path }}
  when: registry_tls_key is defined

- name: Write configuration
  copy: content="{{ registry_config | to_nice_yaml }}" dest={{ registry_config_file_path }}
  when: registry_config is defined

- name: Using default config
  copy: content="{{ __registry_default_config | to_nice_yaml }}" dest={{ registry_config_file_path }}
  when: registry_config is not defined

- name: Start Docker registry
  systemd:
    enabled: yes
    state: started
    daemon_reload: yes
    name: docker-registry.service
