---
- name: Converge
  hosts: all
  vars:
    ansible_user: root
    registry_tls_cert_path: /etc/ssl/certs/ssl-cert-snakeoil.pem
    registry_tls_key_path: /etc/ssl/private/ssl-cert-snakeoil.key
  tasks:
    - name: "Include luxor.registry"
      include_role:
        name: "luxor.registry"
