- name: prepare
  hosts: all
  tasks:
    - name: install ssl-cert
      apt:
        name: ssl-cert
        update_cache: yes
    - name: install docker
      shell: curl https://get.docker.com | sh
